"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { addAudit, upsertEvidence } from "@/lib/db";
import { syncProviders } from "@/lib/integrations/sync";
import { publishGitHubDecisionForSlug } from "@/lib/integrations/github-checks";
const result=(message:string)=>({message});
export async function refreshReleaseAction(_: {message:string}, formData:FormData){ const slug=z.string().min(1).parse(formData.get("slug")); try{const sync=await syncProviders(slug); revalidatePath(`/releases/${slug}`); revalidatePath("/"); return result(`${sync.updated} items refreshed${sync.errors.length?`; ${sync.errors.length} provider warning(s)`:""}.`);}catch(error){return result(error instanceof Error?error.message:"Refresh failed");}}
export async function addEvidenceAction(_: {message:string}, formData:FormData){ const schema=z.object({slug:z.string().min(1),key:z.string().min(1),category:z.enum(["intent","engineering","experience","operations","launch"]),label:z.string().min(1),description:z.string().min(4),status:z.enum(["passed","warning","failed","pending"]),owner:z.string().optional(),required:z.string().optional()}); const parsed=schema.safeParse(Object.fromEntries(formData)); if(!parsed.success)return result(parsed.error.issues[0]?.message??"Invalid evidence"); await upsertEvidence(parsed.data.slug,{key:parsed.data.key,category:parsed.data.category,label:parsed.data.label,description:parsed.data.description,status:parsed.data.status,required:parsed.data.required==="on",source:"Manual",owner:parsed.data.owner||null}); await addAudit(parsed.data.slug,"evidence_added",parsed.data.owner||"Manual reviewer",`${parsed.data.label} marked ${parsed.data.status}.`); revalidatePath(`/releases/${parsed.data.slug}`); revalidatePath("/"); return result("Evidence saved.");}
export async function decideReleaseAction(_: {message:string}, formData:FormData){ const schema=z.object({slug:z.string().min(1),actor:z.string().min(2),note:z.string().min(12),decision:z.enum(["approved","override","blocked"])}); const parsed=schema.safeParse(Object.fromEntries(formData)); if(!parsed.success)return result(parsed.error.issues[0]?.message??"Invalid decision"); await addAudit(parsed.data.slug,parsed.data.decision,parsed.data.actor,parsed.data.note); let publishWarning=""; try { const published=await publishGitHubDecisionForSlug(parsed.data.slug); if (!published.published && published.reason === "not-configured") publishWarning=" GitHub check was not configured."; } catch (error) { publishWarning=` GitHub check warning: ${error instanceof Error ? error.message : "publish failed"}.`; } revalidatePath(`/releases/${parsed.data.slug}`); revalidatePath("/"); return result(`Decision recorded.${publishWarning}`);}
