"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Search } from "lucide-react";
import { evaluateRelease } from "@/lib/decision";
import type { ReleaseCandidate, ReleaseDecision } from "@/lib/types";
import { Card, Pill, decisionTone, riskTone } from "@/components/ui";

const filters: Array<[string, ReleaseDecision | "all"]> = [["All","all"],["Blocked","blocked"],["Needs attention","needs_attention"],["Ready","ready"]];
export function ReleaseList({ releases }: { releases: ReleaseCandidate[] }) {
  const [query,setQuery]=useState(""); const [filter,setFilter]=useState<ReleaseDecision|"all">("all");
  const visible=useMemo(()=>releases.filter((release)=>{const decision=evaluateRelease(release).decision;const matchesFilter=filter==="all"||decision===filter;const haystack=`${release.title} ${release.summary} ${release.repository} ${release.owner}`.toLowerCase();return matchesFilter&&haystack.includes(query.toLowerCase());}),[releases,filter,query]);
  return <div><div className="mt-7 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 sm:flex-row sm:items-center sm:justify-between"><label className="relative block flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><span className="sr-only">Search releases</span><input value={query} onChange={(event)=>setQuery(event.target.value)} className="field pl-9" placeholder="Search release, repository, or owner"/></label><div className="flex gap-1 overflow-x-auto">{filters.map(([label,value])=><button type="button" key={value} onClick={()=>setFilter(value)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-semibold ${filter===value?"bg-slate-950 text-white":"text-slate-600 hover:bg-slate-100"}`}>{label}</button>)}</div></div><div className="mt-4 grid gap-4">{visible.map((release)=>{const result=evaluateRelease(release);return <Link href={`/releases/${release.slug}`} key={release.id}><Card className="grid gap-4 p-5 transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-sm md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap gap-2"><Pill tone={decisionTone(result.decision)}>{result.decision.replace("_"," ")}</Pill><Pill tone={riskTone(release.riskLevel)}>{release.riskLevel} risk</Pill></div><h2 className="mt-3 text-lg font-semibold text-slate-950">{release.title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{release.summary}</p><p className="mt-3 text-xs font-medium text-slate-500">{release.repository} · {release.commitSha} · Owner {release.owner}</p></div><div className="flex items-center gap-4"><div className="text-right"><p className="text-xl font-semibold">{result.passedRequiredCount}/{result.requiredCount}</p><p className="text-xs text-slate-500">required proof</p></div><ArrowRight className="size-5 text-slate-400"/></div></Card></Link>})}{!visible.length&&<Card className="p-10 text-center"><p className="font-semibold text-slate-900">No releases match this view</p><p className="mt-2 text-sm text-slate-500">Clear the search or choose another decision state.</p></Card>}</div></div>;
}
