import Link from "next/link";
import { ArrowRight, Clock3, ExternalLink, Gauge, GitPullRequest, ShieldAlert, Sparkles } from "lucide-react";
import { effectiveEvidence, evaluateRelease } from "@/lib/decision";
import { evidenceCategories, type ReleaseCandidate } from "@/lib/types";
import { releaseStages } from "@/lib/stages";
import { Card, Pill, StatusIcon, decisionTone, riskTone } from "@/components/ui";

const names = { intent: "Intent", engineering: "Engineering", experience: "Experience", operations: "Operations", launch: "Launch" };
export function ReleaseDashboard({ release }: { release: ReleaseCandidate }) {
  const result = evaluateRelease(release); const evidence = effectiveEvidence(release); const stages = releaseStages(release); const policyEvidence = evidenceCategories.map((category) => { const items = evidence.filter((item) => item.category === category && item.required); return { category, total: items.length, passed: items.filter((item) => item.status === "passed").length }; });
  const tone = decisionTone(result.decision); const hero = tone === "green" ? "border-emerald-200 bg-emerald-50/70" : tone === "amber" ? "border-amber-200 bg-amber-50/70" : "border-red-200 bg-red-50/65";
  return <div className="space-y-5">
    <Card className={`overflow-hidden border ${hero}`}><div className="grid gap-6 p-6 md:grid-cols-[1fr_auto] md:p-8"><div>
      <div className="mb-4 flex flex-wrap items-center gap-2"><Pill tone={tone}>{result.decision.replace("_", " ").toUpperCase()}</Pill><Pill tone={riskTone(release.riskLevel)}>{release.riskLevel.toUpperCase()} RISK</Pill><span className="text-xs font-medium text-slate-500">{release.environment}</span></div>
      <p className="text-sm font-semibold text-slate-500">Current release candidate</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950 md:text-4xl">{release.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{release.summary}</p>
      <div className="mt-6 flex flex-wrap items-center gap-3"><Link href={`/releases/${release.slug}`} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">{result.decision === "ready" ? "Review release" : "Resolve blockers"}<ArrowRight className="size-4" /></Link>{release.previewUrl && <a href={release.previewUrl} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">Open preview<ExternalLink className="size-4" /></a>}</div>
    </div><div className="min-w-56 self-center rounded-2xl border border-white/80 bg-white/80 p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Decision</p><p className="mt-2 text-xl font-semibold text-slate-950">{result.headline}</p><p className="mt-2 text-sm leading-5 text-slate-600">{result.summary}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-slate-950" style={{ width: `${Math.round(result.passedRequiredCount / Math.max(result.requiredCount,1) * 100)}%` }} /></div><p className="mt-2 text-xs font-medium text-slate-600">{result.passedRequiredCount} of {result.requiredCount} required proofs passed</p></div></div></Card>
    <div className="grid gap-4 md:grid-cols-5">{policyEvidence.map((group) => <Link key={group.category} href={`/releases/${release.slug}#${group.category}`} className="rounded-2xl border border-slate-200 bg-white p-4 transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-800">{names[group.category]}</p><span className="text-sm font-semibold text-slate-950">{group.passed}<span className="text-slate-600">/{group.total}</span></span></div><div className="mt-3 flex gap-1">{Array.from({ length: Math.max(group.total,1) }).map((_, index) => <span key={index} className={`h-1.5 flex-1 rounded-full ${index < group.passed ? "bg-emerald-500" : "bg-slate-200"}`} />)}</div></Link>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
      <Card><div className="border-b border-slate-100 p-5"><div className="flex items-center gap-2"><ShieldAlert className="size-4 text-slate-500"/><h2 className="font-semibold text-slate-950">Action queue</h2></div><p className="mt-1 text-sm text-slate-500">Only items that need a human decision.</p></div><div className="divide-y divide-slate-100">{result.blockers.length ? result.blockers.slice(0,5).map((item) => <Link href={`/releases/${release.slug}#${item.category}`} key={item.key} className="flex items-start gap-3 p-5 hover:bg-slate-50"><StatusIcon status={item.status} className="mt-0.5 size-5"/><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-slate-900">{item.label}</span><span className="mt-1 block text-sm text-slate-600">{item.description}</span></span><span className="text-xs font-medium text-slate-500">{item.owner ?? "Unassigned"}</span></Link>) : <div className="p-8 text-center"><Sparkles className="mx-auto size-6 text-emerald-600"/><p className="mt-2 font-semibold text-slate-900">No human action required</p><p className="mt-1 text-sm text-slate-500">All required proof is present.</p></div>}</div></Card>
      <div className="space-y-5"><Card className="p-5"><div className="flex items-center gap-2"><Gauge className="size-4 text-slate-500"/><h2 className="font-semibold">Risk policy</h2></div><div className="mt-4 flex items-center justify-between"><span className="text-sm text-slate-500">Overall risk</span><Pill tone={riskTone(release.riskLevel)}>{release.riskLevel}</Pill></div><p className="mt-4 text-sm leading-6 text-slate-600">Policy requirements were selected from the changed files. Sensitive billing, authentication, data, and permission paths receive stronger human gates.</p></Card>
      <Card className="p-5"><div className="flex items-center gap-2"><Clock3 className="size-4 text-slate-500"/><h2 className="font-semibold">After release</h2></div><p className="mt-3 text-sm leading-6 text-slate-600">Observe errors, analytics confirmation, and rollout health before declaring the release complete.</p><div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm text-slate-600"><GitPullRequest className="size-4"/>30-minute observation window</div></Card></div>
    </div>
    <Card className="p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-950">Release path</h2><span className="text-xs text-slate-500">Derived from current evidence</span></div><div className="mt-5 grid grid-cols-3 gap-3 sm:grid-cols-6">{stages.map((stage) => <div key={stage.name} className="min-w-0"><div className={`h-1.5 rounded-full ${stage.status === "passed" ? "bg-emerald-500" : stage.status === "failed" ? "bg-red-500" : stage.status === "warning" ? "bg-amber-400" : stage.status === "pending" ? "bg-violet-400" : "bg-slate-200"}`}/><p className="mt-2 truncate text-xs font-medium text-slate-600">{stage.name}</p></div>)}</div></Card>
  </div>;
}
