import { ExternalLink } from "lucide-react";
import { effectiveEvidence, evaluateRelease } from "@/lib/decision";
import { evidenceCategories, type ReleaseCandidate } from "@/lib/types";
import { Card, Pill, StatusIcon, decisionTone } from "@/components/ui";
import { DecisionForm, EvidenceForm, RefreshForm } from "@/components/release-forms";
const names = { intent: "Intent", engineering: "Engineering", experience: "Experience", operations: "Operations", launch: "Launch" };
export function ReleaseDetail({ release }: { release: ReleaseCandidate }) { const decision = evaluateRelease(release); const evidence = effectiveEvidence(release); return <div className="space-y-6">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex gap-2"><Pill tone={decisionTone(decision.decision)}>{decision.decision.replace("_", " ")}</Pill><Pill>{release.environment}</Pill></div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{release.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{release.summary}</p></div><RefreshForm slug={release.slug}/></div>
  <Card className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4">{[["Owner",release.owner],["Repository",release.repository],["Branch",release.branch],["Commit",release.commitSha]].map(([label,value]) => <div key={label}><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 truncate text-sm font-semibold text-slate-900">{value}</p></div>)}</Card>
  {evidenceCategories.map((category) => { const items = evidence.filter((item) => item.category === category).sort((a,b) => Number(b.required)-Number(a.required)); return <Card key={category} className="overflow-hidden" ><div id={category} className="scroll-mt-20 border-b border-slate-100 p-5"><h2 className="font-semibold text-slate-950">{names[category]}</h2><p className="mt-1 text-sm text-slate-500">{items.filter((i)=>i.status==="passed").length} of {items.length} checks passed</p></div><div className="divide-y divide-slate-100">{items.map((item) => <div key={item.key} className="flex items-start gap-3 p-5"><StatusIcon status={item.status} className="mt-0.5 size-5"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-900">{item.label}</p>{item.required && <Pill>required</Pill>}</div><p className="mt-1 text-sm leading-5 text-slate-600">{item.description}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs font-medium text-slate-500"><span>{item.source}</span>{item.owner && <span>Owner: {item.owner}</span>}<span>{new Date(item.observedAt).toLocaleString()}</span>{item.sourceUrl && <a className="inline-flex items-center gap-1 text-violet-700" href={item.sourceUrl}>Source<ExternalLink className="size-3"/></a>}</div></div></div>)}</div></Card>; })}
  <div className="grid gap-5 lg:grid-cols-2"><EvidenceForm slug={release.slug}/><DecisionForm slug={release.slug} current={decision.decision}/></div>
  <Card><div className="border-b border-slate-100 p-5"><h2 className="font-semibold">Decision timeline</h2><p className="mt-1 text-sm text-slate-500">A durable record of evidence and human judgment.</p></div><ol className="divide-y divide-slate-100">{[...release.audit].reverse().map((event) => <li key={event.id} className="grid gap-1 p-5 sm:grid-cols-[140px_1fr_auto]"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{event.action.replace("_"," ")}</span><span className="text-sm text-slate-700">{event.note}</span><span className="text-xs text-slate-500">{event.actor} · {new Date(event.createdAt).toLocaleString()}</span></li>)}</ol></Card>
</div>; }
