import { CheckCircle2, CircleDashed, Clock3, Radio, ShieldCheck, Wrench } from "lucide-react";
import { integrationHealth } from "@/lib/integrations/health";
import { Card, Pill } from "@/components/ui";

function tone(status: string) { return status === "connected" ? "green" : status === "fixture" ? "slate" : "amber"; }
function icon(status: string) { return status === "connected" ? CheckCircle2 : status === "fixture" ? CircleDashed : Wrench; }

export const dynamic = "force-dynamic";
export default async function IntegrationsPage() {
  const integrations = await integrationHealth();
  return <div className="space-y-7">
    <div><p className="eyebrow">INTEGRATIONS</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em] text-slate-950 sm:text-4xl">A five-minute path to live release evidence.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Start with read-only backfill, then add signed webhooks for live updates. The editor bridge submits approved evidence without scraping private prompts or source files.</p></div>
    <div className="grid gap-4 xl:grid-cols-2">{integrations.map((item) => { const Icon = icon(item.status); return <Card key={item.provider} className="overflow-hidden"><div className="p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-slate-100"><Icon className={`size-5 ${item.status === "connected" ? "text-emerald-600" : item.status === "fixture" ? "text-slate-500" : "text-amber-600"}`}/></span><div><h2 className="font-semibold text-slate-950">{item.name}</h2><p className="mt-1 text-sm leading-5 text-slate-600">{item.detail}</p></div></div><Pill tone={tone(item.status)}>{item.status}</Pill></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><Clock3 className="size-3.5"/>Last event</div><p className="mt-2 text-sm font-semibold text-slate-800">{item.lastSync ? new Date(item.lastSync).toLocaleString() : "Waiting for first event"}</p><p className="mt-1 text-xs text-slate-500">{item.eventCount ?? 0} events received</p></div><div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><Radio className="size-3.5"/>Endpoint</div><code className="mt-2 block overflow-x-auto text-xs font-semibold text-slate-700">{item.endpoint}</code></div></div>
      <div className="mt-4 rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-slate-500"/><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Access boundary</p></div><ul className="mt-2 space-y-1.5 text-sm text-slate-700">{item.permissions.map((permission) => <li key={permission} className="flex gap-2"><span className="text-slate-400">•</span>{permission}</li>)}</ul></div>
    </div></Card>; })}</div>
    <Card className="p-5"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="font-semibold text-slate-950">Recommended activation order</h2><p className="mt-1 text-sm text-slate-500">Useful immediately in fixture mode; each step increases freshness without changing the product model.</p></div><div className="grid flex-1 gap-2 sm:grid-cols-3 xl:max-w-3xl xl:grid-cols-6">{["Connect read API","Select repo or issue","Add signing secret","Register webhook","Send editor run","Verify live event"].map((step,index) => <div key={step} className="rounded-xl bg-slate-50 p-3"><span className="text-xs font-semibold text-violet-700">0{index+1}</span><p className="mt-1 text-xs font-semibold leading-5 text-slate-800">{step}</p></div>)}</div></div></Card>
    <Card className="p-5"><h2 className="font-semibold text-slate-950">Editor bridge quick start</h2><p className="mt-1 text-sm text-slate-500">Run from Cursor, Codex, Claude Code, or any integrated terminal.</p><pre className="mt-4 overflow-x-auto rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-100"><code>{`release-room complete \\\n  --release team-billing-settings \\\n  --editor Cursor \\\n  --model "Grok 4.5 Very Fast" \\\n  --task SHE-71 \\\n  --checks lint,typecheck,test,build`}</code></pre><p className="mt-3 text-xs text-slate-500">See <code>docs/EDITOR-BRIDGE.md</code> for dry-run, retries, and vendor-neutral examples.</p></Card>
  </div>;
}
